import { TypeTheme } from './Box/Box';
export declare const sizeX1Px = 4;
export declare const sizeX2Px: number;
export declare const sizeX3Px: number;
export declare const sizeX4Px: number;
export declare const sizeX5Px: number;
export declare const sizeX6Px: number;
export declare const sizeX8Px: number;
export declare const sizeX10Px: number;
export declare const sizeX12Px: number;
export declare const sizeX16Px: number;
export declare const sizeX1Rem = 0.25;
export declare const sizeX2Rem: number;
export declare const sizeX3Rem: number;
export declare const sizeX4Rem: number;
export declare const sizeX5Rem: number;
export declare const sizeX6Rem: number;
export declare const sizeX8Rem: number;
export declare const sizeX10Rem: number;
export declare const sizeX12Rem: number;
export declare const sizeX16Rem: number;
export declare const borderSizeX1Px = 1;
export declare const borderSizeX2Px = 2;
export declare const borderSizeX1Rem = 0.0625;
export declare const borderSizeX2Rem = 0.125;
export declare const colorWhite = "#FFFEFC";
export declare const colorBlack = "#1E1B18";
export declare const colorDarkShade1: string;
export declare const colorDarkShade2: string;
export declare const colorDarkShade3: string;
export declare const colorLightShade1: string;
export declare const colorLightShade2: string;
export declare const colorLightShade3: string;
export declare const colorAccent1Shade1: string;
export declare const colorAccent1Shade2: string;
export declare const colorAccent1Shade3: string;
export declare const colorAccent2Shade1: string;
export declare const colorAccent2Shade2: string;
export declare const colorAccent2Shade3: string;
export declare const colorPositiveShade1: string;
export declare const colorPositiveShade2: string;
export declare const colorPositiveShade3: string;
export declare const colorNegativeShade1: string;
export declare const colorNegativeShade2: string;
export declare const colorNegativeShade3: string;
export declare const colorHighlight: string;
export declare const themeDay: {
    colorBackgroundShade1: string;
    colorBackgroundShade2: string;
    colorBackgroundShade3: string;
    colorTextShade1: string;
    colorTextShade2: string;
    colorTextShade3: string;
    colorAccentShade1: string;
    colorAccentShade2: string;
    colorAccentShade3: string;
};
export declare const themeNight: {
    colorBackgroundShade1: string;
    colorBackgroundShade2: string;
    colorBackgroundShade3: string;
    colorTextShade1: string;
    colorTextShade2: string;
    colorTextShade3: string;
    colorAccentShade1: string;
    colorAccentShade2: string;
    colorAccentShade3: string;
};
export declare const themes: {
    [key in TypeTheme]: {
        [key: string]: string;
    };
};
export declare const themesOpposite: {
    [key in TypeTheme]: TypeTheme;
};
export declare const themePropNameCSSMap: {
    colorBackgroundShade1: string;
    colorBackgroundShade2: string;
    colorBackgroundShade3: string;
    colorTextShade1: string;
    colorTextShade2: string;
    colorTextShade3: string;
    colorAccentShade1: string;
    colorAccentShade2: string;
    colorAccentShade3: string;
};
export declare const transitionTimeFast = 200;
export declare const transitionTimeBox = 400;
export declare const transitionTimeSlow = 800;
export declare const transitionTimingFunction: number[];
//# sourceMappingURL=variables.d.ts.map