language: node_js
cache: yarn
branches:
  only:
    - master
before_script:
  - yarn global add firebase-tools
script:
  - yarn lint
  - yarn test
  - yarn build:static
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
