language: node_js
cache: yarn
branches:
  only:
  - master
script:
- yarn lint
- yarn build:lib
after_success:
- npm run travis-deploy-once "npm run semantic-release"
- yarn build:docs
- yarn build:site
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: AmuTN6QNkgF0kkbE/2eE7M8RGn+h23iQVdL16cr7sxfTjJ0MvRxGWHEstnf5SqZGzw6IqwERysyArwEe80kj1yWX+8QJdXWme1h1Pit4RrA10k78Xl5YWcaqoBKlVsISS0w/yoCU4AuWr2UkE3gvZBngLCA7qPi7GxGMwxILBbOgzotLUERghVREYAV5CUYhBsy6F/qldG6Rxnx26TbOSeDKsYE8JZGKikxcYiFnQ3KJZZZMSl1rCb3ljbCD6TJP6xmMNr3sq/Jj7ilV3+d14R+uRz2Zz7VSQAyOPQKxj2NQF3lQ+V6rAgtKWqPDSeUR11kEPL9jXLYpqeF2Aghhwxp5O7vQWNed36q8g7Y4va7yaTwOA0R7GaJaSQQRfjL7wdss06XFwTK7iH8gsDbWc7dbZhK+coPLIfOEU19cU8MESKEvofb7iZf3elJu2gIkBAZF2537SmBfEY+Jc15zMzXMY1aHAL5J6EOtGtLYjTy2YGg5lNgsmqO0Gm2D5hjDPrs7/f+XV6BieOpb75xjIqZ6sf6YyiNEMKpMB62xEJ/fU2w5gVO1j6YLyRCxd1Hq3NAWI474tJMQpQuUDBVLyqr4zySk61EY351U2K7EPOZx8ZUmS3jp/wJezx/LrsAtf/NW6N+MukG4pEMzsdZ02a8i9kxe0DleVdE4Be2LmQs=
