language: node_js
cache: yarn
branches:
  only:
    - master
script:
  - yarn lint
  - yarn test
  - yarn build:package
  - yarn build:site
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
