import { forwardRef } from 'react';
import { Box, BoxProps } from 'preshape';

const Pictogram: React.ForwardRefRenderFunction<SVGSVGElement, BoxProps> = (
  props,
  ref
) => {
  return (
    <Box
      {...props}
      className="Pictogram"
      ref={ref}
      tag="svg"
      viewBox="0 0 248 96"
    >
      {
        <svg viewBox="0 0 248 96" xmlns="http://www.w3.org/2000/svg" {...props}>
          <g
            id="pictogram-grid_svg__pictogram-grid"
            stroke="none"
            strokeWidth={1}
            fill="none"
            fillRule="evenodd"
          >
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-22"
              fill="var(--color-text-shade-1)"
              x={4}
              y={8}
              width={75}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-25"
              fill="var(--color-text-shade-1)"
              x={4}
              y={36}
              width={75}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-28"
              fill="var(--color-text-shade-1)"
              x={4}
              y={64}
              width={75}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-24"
              fill="var(--color-text-shade-1)"
              x={169}
              y={8}
              width={75}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-26"
              fill="var(--color-text-shade-1)"
              x={169}
              y={36}
              width={75}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-23"
              fill="var(--color-text-shade-1)"
              x={84}
              y={8}
              width={80}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-27"
              fill="var(--color-text-shade-1)"
              x={84}
              y={36}
              width={80}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-grid_svg__Rectangle-Copy-29"
              fill="var(--color-text-shade-1)"
              x={84}
              y={64}
              width={80}
              height={24}
              rx={6}
            />
            <circle
              id="pictogram-grid_svg__Oval"
              fill="var(--color-accent-shade-4)"
              cx={16}
              cy={20}
              r={4}
            />
            <circle
              id="pictogram-grid_svg__Oval-Copy"
              fill="var(--color-accent-shade-4)"
              cx={180}
              cy={48}
              r={4}
            />
            <circle
              id="pictogram-grid_svg__Oval-Copy-2"
              fill="var(--color-accent-shade-4)"
              cx={96}
              cy={76}
              r={4}
            />
          </g>
        </svg>
      }
    </Box>
  );
};

export default forwardRef(Pictogram);
