import { Box, BoxProps } from 'preshape';
import { forwardRef } from 'react';
export const Pictogram = forwardRef<SVGSVGElement, BoxProps>((props, ref) => {
  return (
    <Box
      {...props}
      className="Pictogram"
      ref={ref}
      tag="svg"
      viewBox="0 0 248 96"
    >
      {
        <svg viewBox="0 0 248 96" xmlns="http://www.w3.org/2000/svg" {...props}>
          <g
            id="pictogram-flex_svg__pictogram-flex"
            stroke="none"
            strokeWidth={1}
            fill="none"
            fillRule="evenodd"
          >
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-5"
              fill="var(--color-text-shade-1)"
              x={64}
              y={8}
              width={120}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-9"
              fill="var(--color-text-shade-1)"
              x={188}
              y={8}
              width={56}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-6"
              fill="var(--color-text-shade-1)"
              x={97}
              y={36}
              width={56}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-4"
              fill="var(--color-text-shade-1)"
              x={4}
              y={64}
              width={40}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-13"
              fill="var(--color-text-shade-1)"
              x={48}
              y={64}
              width={29}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-14"
              fill="var(--color-text-shade-1)"
              x={172}
              y={64}
              width={29}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-11"
              fill="var(--color-text-shade-1)"
              x={205}
              y={64}
              width={39}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-10"
              fill="var(--color-text-shade-1)"
              x={4}
              y={8}
              width={57}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-7"
              fill="var(--color-text-shade-1)"
              x={4}
              y={36}
              width={89}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-12"
              fill="var(--color-text-shade-1)"
              x={80}
              y={64}
              width={89}
              height={24}
              rx={6}
            />
            <rect
              id="pictogram-flex_svg__Rectangle-Copy-8"
              fill="var(--color-text-shade-1)"
              x={157}
              y={36}
              width={87}
              height={24}
              rx={6}
            />
            <circle
              id="pictogram-flex_svg__Oval"
              fill="var(--color-accent-shade-4)"
              cx={16}
              cy={20}
              r={4}
            />
            <circle
              id="pictogram-flex_svg__Oval-Copy"
              fill="var(--color-accent-shade-4)"
              cx={236}
              cy={48}
              r={4}
            />
            <circle
              id="pictogram-flex_svg__Oval-Copy-2"
              fill="var(--color-accent-shade-4)"
              cx={124}
              cy={76}
              r={4}
            />
          </g>
        </svg>
      }
    </Box>
  );
});
