/** AUTO GENERATED **/
import { Box, BoxProps } from 'preshape';
import { forwardRef } from 'react';
export const Pictogram = forwardRef<SVGSVGElement, BoxProps>((props, ref) => {
  return (
    <Box
      {...props}
      className="Pictogram"
      ref={ref}
      tag="svg"
      viewBox="0 0 248 96"
    >
      {
        <svg
          viewBox="0 0 248 96"
          xmlns="http://www.w3.org/2000/svg"
          xmlnsXlink="http://www.w3.org/1999/xlink"
          {...props}
        >
          <title>{'pictogram-text'}</title>
          <g stroke="none" strokeWidth={1} fill="none" fillRule="evenodd">
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={30}
              width={144}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={46}
              width={140}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={70}
              width={140}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={38}
              width={123}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={62}
              width={123}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={54}
              width={96}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-text-shade-1)"
              x={40}
              y={78}
              width={96}
              height={4}
              rx={2}
            />
            <rect
              fill="var(--color-accent-shade-4)"
              x={40}
              y={14}
              width={168}
              height={8}
              rx={2}
            />
          </g>
        </svg>
      }
    </Box>
  );
});
