import { Box, BoxProps } from 'preshape';
import { forwardRef } from 'react';
export const Pictogram = forwardRef<SVGSVGElement, BoxProps>((props, ref) => {
  return (
    <Box
      {...props}
      className="Pictogram"
      ref={ref}
      tag="svg"
      viewBox="0 0 248 96"
    >
      {
        <svg viewBox="0 0 248 96" xmlns="http://www.w3.org/2000/svg" {...props}>
          <g
            id="pictogram-code_svg__pictogram-code"
            stroke="none"
            strokeWidth={1}
            fill="none"
            fillRule="evenodd"
          >
            <g id="pictogram-code_svg__Group" transform="translate(48 12)">
              <rect
                id="pictogram-code_svg__Rectangle"
                fill="var(--color-text-shade-1)"
                x={0}
                y={0}
                width={4}
                height={72}
                rx={2}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-5"
                fill="var(--color-text-shade-1)"
                x={16}
                y={0}
                width={32}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-6"
                fill="var(--color-accent-shade-4)"
                x={24}
                y={16}
                width={16}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-20"
                fill="var(--color-accent-shade-4)"
                x={68}
                y={0}
                width={16}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-21"
                fill="var(--color-accent-shade-4)"
                x={120}
                y={32}
                width={16}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-8"
                fill="var(--color-text-shade-1)"
                x={24}
                y={48}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-13"
                fill="var(--color-text-shade-1)"
                x={52}
                y={0}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-11"
                fill="var(--color-text-shade-1)"
                x={60}
                y={32}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-18"
                fill="var(--color-text-shade-1)"
                x={96}
                y={16}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-19"
                fill="var(--color-text-shade-1)"
                x={112}
                y={16}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-15"
                fill="var(--color-text-shade-1)"
                x={76}
                y={32}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-25"
                fill="var(--color-text-shade-1)"
                x={140}
                y={32}
                width={12}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-10"
                fill="var(--color-text-shade-1)"
                x={40}
                y={48}
                width={20}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-22"
                fill="var(--color-text-shade-1)"
                x={88}
                y={0}
                width={20}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-9"
                fill="var(--color-text-shade-1)"
                x={16}
                y={64}
                width={48}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-12"
                fill="var(--color-text-shade-1)"
                x={44}
                y={16}
                width={48}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-14"
                fill="var(--color-text-shade-1)"
                x={64}
                y={48}
                width={8}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-24"
                fill="var(--color-accent-shade-4)"
                x={68}
                y={64}
                width={8}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-23"
                fill="var(--color-text-shade-1)"
                x={76}
                y={48}
                width={36}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-7"
                fill="var(--color-text-shade-1)"
                x={32}
                y={32}
                width={24}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-16"
                fill="var(--color-text-shade-1)"
                x={92}
                y={32}
                width={24}
                height={8}
                rx={4}
              />
              <rect
                id="pictogram-code_svg__Rectangle-Copy-17"
                fill="var(--color-text-shade-1)"
                x={116}
                y={48}
                width={24}
                height={8}
                rx={4}
              />
            </g>
          </g>
        </svg>
      }
    </Box>
  );
});
