import * as React from 'react';

function SvgPictogramTable(props) {
  return (
    <svg viewBox="0 0 248 96" xmlns="http://www.w3.org/2000/svg" {...props}>
      <g
        id="pictogram-table_svg__pictogram-table"
        stroke="none"
        strokeWidth={1}
        fill="none"
        fillRule="evenodd"
      >
        <rect
          id="pictogram-table_svg__Rectangle-Copy-2"
          fill="var(--color-text--shade-1)"
          x={4}
          y={32}
          width={240}
          height={4}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-5"
          fill="var(--color-text--shade-1)"
          x={24}
          y={16}
          width={56}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-8"
          fill="var(--color-text--shade-1)"
          x={24}
          y={44}
          width={72}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-14"
          fill="var(--color-accent--shade-4)"
          x={12}
          y={44}
          width={8}
          height={8}
          rx={4}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-13"
          fill="var(--color-text--shade-1)"
          x={24}
          y={70}
          width={80}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-15"
          fill="var(--color-accent--shade-4)"
          x={12}
          y={70}
          width={8}
          height={8}
          rx={4}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-9"
          fill="var(--color-text--shade-1)"
          x={144}
          y={44}
          width={24}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-11"
          fill="var(--color-text--shade-1)"
          x={204}
          y={44}
          width={32}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-10"
          fill="var(--color-text--shade-1)"
          x={144}
          y={70}
          width={24}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-12"
          fill="var(--color-text--shade-1)"
          x={204}
          y={70}
          width={32}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-6"
          fill="var(--color-text--shade-1)"
          x={120}
          y={16}
          width={48}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-7"
          fill="var(--color-text--shade-1)"
          x={180}
          y={16}
          width={56}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-3"
          fill="var(--color-text--shade-1)"
          x={4}
          y={60}
          width={240}
          height={2}
          rx={1}
        />
        <rect
          id="pictogram-table_svg__Rectangle-Copy-4"
          fill="var(--color-text--shade-1)"
          x={4}
          y={86}
          width={240}
          height={2}
          rx={1}
        />
      </g>
    </svg>
  );
}

export default SvgPictogramTable;
