import * as React from 'react';

function SvgPictogramCode(props) {
  return (
    <svg viewBox="0 0 248 96" xmlns="http://www.w3.org/2000/svg" {...props}>
      <g
        id="pictogram-code_svg__pictogram-code"
        stroke="none"
        strokeWidth={1}
        fill="none"
        fillRule="evenodd"
      >
        <rect
          id="pictogram-code_svg__Rectangle"
          fill="var(--color-text-shade-1)"
          x={48}
          y={12}
          width={4}
          height={72}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-5"
          fill="var(--color-text-shade-1)"
          x={64}
          y={12}
          width={32}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-6"
          fill="var(--color-accent-shade-4)"
          x={72}
          y={28}
          width={16}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-20"
          fill="var(--color-accent-shade-4)"
          x={116}
          y={12}
          width={16}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-21"
          fill="var(--color-accent-shade-4)"
          x={168}
          y={44}
          width={16}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-8"
          fill="var(--color-text-shade-1)"
          x={72}
          y={60}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-13"
          fill="var(--color-text-shade-1)"
          x={100}
          y={12}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-11"
          fill="var(--color-text-shade-1)"
          x={108}
          y={44}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-18"
          fill="var(--color-text-shade-1)"
          x={144}
          y={28}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-19"
          fill="var(--color-text-shade-1)"
          x={160}
          y={28}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-15"
          fill="var(--color-text-shade-1)"
          x={124}
          y={44}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-25"
          fill="var(--color-text-shade-1)"
          x={188}
          y={44}
          width={12}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-10"
          fill="var(--color-text-shade-1)"
          x={88}
          y={60}
          width={20}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-22"
          fill="var(--color-text-shade-1)"
          x={136}
          y={12}
          width={20}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-9"
          fill="var(--color-text-shade-1)"
          x={64}
          y={76}
          width={48}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-12"
          fill="var(--color-text-shade-1)"
          x={92}
          y={28}
          width={48}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-14"
          fill="var(--color-text-shade-1)"
          x={112}
          y={60}
          width={8}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-24"
          fill="var(--color-accent-shade-4)"
          x={116}
          y={76}
          width={8}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-23"
          fill="var(--color-text-shade-1)"
          x={124}
          y={60}
          width={36}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-7"
          fill="var(--color-text-shade-1)"
          x={80}
          y={44}
          width={24}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-16"
          fill="var(--color-text-shade-1)"
          x={140}
          y={44}
          width={24}
          height={8}
          rx={1}
        />
        <rect
          id="pictogram-code_svg__Rectangle-Copy-17"
          fill="var(--color-text-shade-1)"
          x={164}
          y={60}
          width={24}
          height={8}
          rx={1}
        />
      </g>
    </svg>
  );
}

export default SvgPictogramCode;
