name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Cache: node_modules"
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.locl') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Install Dependencies"
        run: yarn
      - name: "Test: Linting"
        run: yarn lint
      - name: "Build: Library"
        run: yarn build:lib
      - name: "Deploy: Library"
        run: yarn deploy:lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Build: Docs"
        run: yarn build:docs
      - name: "Build: Site"
        run: yarn build:site
      - name: "Deploy: Site"
        run: "yarn firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}"
