name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Install Dependencies'
        run: yarn
      - name: 'Build package'
        run: yarn workspace preshape build
      - name: 'Linting'
        run: yarn lint
      - name: 'Build site'
        run: yarn workspace site build
      - name: 'Publish package'
        run: yarn deploy:lib
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 'Deploy site'
        run: 'yarn deploy:site --token ${{ secrets.FIREBASE_TOKEN }}'
